In [1]:
import numpy as np

In [2]:
W = np.random.randn(3, 4)
x = np.random.randn(1, 3)
b = np.random.randn(1, 4)

In [3]:
x @ W + b

array([[-1.45176993e-01,  6.55050126e-04, -8.49061396e-01,
        -1.42827399e+00]])

In [4]:
x[0, 1] = 3

In [5]:
x @ W + b

array([[-2.76280458, -0.94728013,  0.5586713 , -3.22510018]])

In [6]:
x

array([[-0.10400495,  3.        ,  0.66144553]])